# Generated by Django 3.2 on 2021-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_products_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update',
            field=models.CharField(choices=[('--', '--'), ('Pending', 'pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('--', '--'), ('Pending', 'pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'delivered')], max_length=200, null=True),
        ),
    ]
