# Generated by Django 3.2 on 2021-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210419_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
