# Generated by Django 3.2 on 2021-04-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_customer1_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer1',
        ),
    ]
