# Generated by Django 3.2 on 2021-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_firstname_users_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='aboutme',
        ),
        migrations.AddField(
            model_name='users',
            name='about_me',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
