# Generated by Django 3.2 on 2021-05-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210525_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
