# Generated by Django 3.2 on 2021-05-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='note',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
