# Generated by Django 3.2 on 2021-05-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_note_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
