# Generated by Django 3.2 on 2021-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
