# Generated by Django 3.2 on 2021-05-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_nutrition_nutritious'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritious',
            name='description_two',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='nutritious',
            name='title2_two',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
