# Generated by Django 3.2 on 2021-05-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210529_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritious',
            old_name='title2_two',
            new_name='title_two',
        ),
    ]
