# Generated by Django 3.2 on 2021-06-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_order_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orders',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_created',
        ),
    ]
