# Generated by Django 3.2 on 2021-06-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_auto_20210603_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
