# Generated by Django 3.2 on 2021-06-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
